version: '3.9'
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
#    volumes:
#      - ./database:/var/lib/postgresql/data
#      - ./migrate.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    depends_on:
      - db
    build: ./
    container_name: restapp
    image: rest_app
    restart: always
    environment:
      POSTGRES_URL: jdbc:postgresql://localhost:5432/postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"