version: '3.9'
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=assql
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./migrate.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    depends_on:
      - db
    build: ./
    container_name: restapp
    image: rest_app
    restart: always
#    environment:
#      db_url: jdbc:postgresql://172.25.0.2:5432/postgres
#      db_username: root
#      db_password: assql
    ports:
      - "8080:8080"