version: '3'
services:
  postgres:
    container_name: 'restproject-postgres'
    image: postgres:latest
    network_mode: bridge
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=assql
      - POSTGRES_DB=postgres
    restart: unless-stopped

  app:
    container_name: 'restproject'
    network_mode: bridge
    build: ./
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql@postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=assql
      - PORT=8080
    depends_on:
      - postgres
